import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@mui/material";
import Sidebar from "@/component/ui/sidebar/Sidebar";
import AppProvider from "@/component/app/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Sidebar />
          <Container
            maxWidth="xl"
            disableGutters
            sx={{
              color: "text.primary",
              backgroundColor: "background.default",
            }}
          >
            {children}
          </Container>
        </AppProvider>
      </body>
    </html>
  );
}
